-- ════════════════════════════════════════════════════════════════
--  RÉINITIALISATION DES DONNÉES — à coller dans Supabase > SQL Editor
--  ⚠️ SUPPRIME TOUTES les données (résidents, journal, présences, paie…)
--  CONSERVE : profiles (ton compte) + app_config (ta config).
-- ════════════════════════════════════════════════════════════════

truncate table
  absences_at,
  activites,
  admissions,
  astreintes,
  budget_demandes,
  budget_enveloppes,
  candidats,
  chambres,
  conges,
  contacts_externes,
  contrats,
  conversations,
  cvs,
  documentation,
  documents_employe,
  documents_resident,
  echeances,
  employes,
  entretiens,
  etats_lieux,
  evaluations,
  fiches_paie,
  formations,
  incidents,
  interventions,
  inventaire,
  journal_entries,
  med_distrib,
  messages,
  nuits,
  plan_soins,
  planning_equipe,
  planning_events,
  pointages,
  ppe,
  presences,
  rapport_contributions,
  repas_jour,
  repertoire,
  residents,
  satisfaction,
  satisfaction_questions,
  transmissions,
  viatrajectoire,
  visites
restart identity cascade;
